# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
     - '*.md'
    branches:
     - develop
     - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
     - main
     - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: install-nuget
        uses: NuGet/setup-nuget@v1.0.5
      - run: nuget restore installer\GearboxInstaller.sln
        
      - name: build-solution
        run: msbuild installer\GearboxInstaller.sln -t:Publish -p:Configuration=Release -p:PublishDir="publish" -p:TargetRuntime=win-x86 -p:SelfContained=true -p:WarningLevel=0 /p:DebugSymbols=false /p:DebugType=None
        
      - name: zip-files
        uses: vimtor/action-zip@v1
        with:
          files: installer\GearboxInstaller\publish\
          dest: gearboxinstaller.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        if: github.event_name == 'pull_request'
        with:
          # Artifact name
          name: gearboxinstaller
          # A file, directory or wildcard pattern that describes what to upload
          path: installer\GearboxInstaller\publish\

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        name: delete-beta-tag
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          delete_release: true # default: false
          tag_name: 'latest-beta' # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release-beta
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/heads/develop')
        with:
          name: 🩸Bleeding Edge🩸
          files: ${{ github.workspace }}\installer\GearboxInstaller\publish\GearboxInstaller.exe
          body_path: patch-notes.md
          prerelease: true
          tag_name: 'latest-beta'
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}\installer\GearboxInstaller\publish\GearboxInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
